# Generated by Django 3.2.6 on 2024-02-09 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('i8n', '0007_auto_20240208_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pumpwoodi8ntranslation',
            options={'verbose_name': 'Pumpwood I8n Translation', 'verbose_name_plural': 'Pumpwood I8n Translations'},
        ),
    ]
