# Generated by Django 5.2.3 on 2026-03-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('row_permission', '0005_rename_pumpwoodrowpermissionpolicyuserm2m_pumpwoodrowpermissionuserm2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumpwoodrowpermission',
            name='code',
            field=models.TextField(blank=True, help_text='A code to indentify the row permission.', null=True, unique=True, verbose_name='Description'),
        ),
    ]
