# Generated by Django 5.2.3 on 2026-06-18
"""Correct verbose_name and help_text on row permission code field."""
from django.db import migrations, models


class Migration(migrations.Migration):
    """Alter PumpwoodRowPermission.code field metadata."""

    dependencies = [
        ('row_permission', '0006_add_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumpwoodrowpermission',
            name='code',
            field=models.TextField(
                blank=True,
                help_text='A code to identify the row permission.',
                null=True,
                unique=True,
                verbose_name='Code'),
        ),
    ]
