# Generated by Django 5.2.3 on 2025-06-25 19:06
from django.db import migrations


def create_default_permission_policies(apps, schema_editor):
    """Updates populated info PumpwoodPermissionPolicy to boolean values."""
    PumpwoodPermissionPolicy = apps.get_model(
        'api_permission', 'PumpwoodPermissionPolicy')
    PumpwoodPermissionPolicyAction = apps.get_model(
        'api_permission', 'PumpwoodPermissionPolicyAction')

    objs = PumpwoodPermissionPolicy.objects.all()
    for x in objs:
        x.can_list = x.can_list_legacy == 'allow'
        x.can_list_without_pag = x.can_list_without_pag_legacy == 'allow'
        x.can_retrieve = x.can_retrieve_legacy == 'allow'
        x.can_retrieve_file = x.can_retrieve_file_legacy == 'allow'
        x.can_delete = x.can_delete_legacy == 'allow'
        x.can_delete_many = x.can_delete_many_legacy == 'allow'
        x.can_delete_file = x.can_delete_file_legacy == 'allow'
        x.can_save = x.can_save_legacy == 'allow'
        x.can_run_actions = x.can_run_actions_legacy == 'allow'
        x.save()

    objs = PumpwoodPermissionPolicyAction.objects.all()
    for x in objs:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('api_permission', '0017_pumpwoodpermissionpolicy_can_delete_and_more'),
    ]

    operations = [
    ]
