# Generated by Django 5.2.3 on 2025-06-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_permission', '0019_remove_pumpwoodpermissionpolicy_can_delete_file_legacy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pumpwoodpermissionpolicygroupm2m',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='pumpwoodpermissionpolicyuserm2m',
            name='priority',
        ),
        migrations.AlterField(
            model_name='pumpwoodpermissionpolicy',
            name='can_delete',
            field=models.BooleanField(blank=True, help_text='Permission to delete object end-point and front-end page', null=True, verbose_name='Delete'),
        ),
        migrations.AlterField(
            model_name='pumpwoodpermissionpolicy',
            name='can_delete_file',
            field=models.BooleanField(blank=True, help_text='Permission to delelte file end-point', null=True, verbose_name='Delete File'),
        ),
        migrations.AlterField(
            model_name='pumpwoodpermissionpolicy',
            name='can_delete_many',
            field=models.BooleanField(blank=True, help_text='Permission to delete many end-point', null=True, verbose_name='Delete Many'),
        ),
        migrations.AlterField(
            model_name='pumpwoodpermissionpolicy',
            name='can_list',
            field=models.BooleanField(blank=True, help_text='Permission to list end-point and front-end page', null=True, verbose_name='List'),
        ),
        migrations.AlterField(
            model_name='pumpwoodpermissionpolicy',
            name='can_list_without_pag',
            field=models.BooleanField(blank=True, help_text='Permission to list without pagination end-point. Return all values associated with query (list paginate 50)', null=True, verbose_name='List Without Pag.'),
        ),
        migrations.AlterField(
            model_name='pumpwoodpermissionpolicy',
            name='can_retrieve',
            field=models.BooleanField(blank=True, help_text='Permission to retrieve end-point and front-end page', null=True, verbose_name='Retrieve'),
        ),
        migrations.AlterField(
            model_name='pumpwoodpermissionpolicy',
            name='can_retrieve_file',
            field=models.BooleanField(blank=True, help_text='Permission to retrieve file end-point', null=True, verbose_name='Retrieve File'),
        ),
        migrations.AlterField(
            model_name='pumpwoodpermissionpolicy',
            name='can_run_actions',
            field=models.BooleanField(blank=True, help_text='Permission to run actions', null=True, verbose_name='Actions'),
        ),
        migrations.AlterField(
            model_name='pumpwoodpermissionpolicy',
            name='can_save',
            field=models.BooleanField(blank=True, help_text='Permission to save end-point and front-end page', null=True, verbose_name='Save'),
        ),
        migrations.AlterField(
            model_name='pumpwoodpermissionpolicyaction',
            name='is_allowed',
            field=models.BooleanField(blank=True, help_text='If user can run or not this action', null=True, verbose_name='Allow/Deny'),
        ),
    ]
