# Generated by Django 5.1.3 on 2026-06-18 16:23
"""Add unique code fields to API permission models."""
from django.db import migrations, models
from slugify import slugify


def _unique_slug_code(text, pk, used_codes, prefix):
    """Build a unique code from text using slugify.

    Args:
        text (str):
            Source text, usually description or action name.
        pk (int):
            Primary key used when slugify returns an empty string.
        used_codes (set):
            Codes already assigned in the same migration run.
        prefix (str):
            Prefix for fallback code when slugify returns empty.

    Returns:
        str:
            Unique slug code.
    """
    base = slugify(text or '')
    if base == '':
        base = '{prefix}-{pk}'.format(prefix=prefix, pk=pk)
    code = base
    suffix = 2
    while code in used_codes:
        code = '{base}-{suffix}'.format(base=base, suffix=suffix)
        suffix += 1
    used_codes.add(code)
    return code


def backfill_permission_codes(apps, schema_editor):
    """Set code from slugified description or action for existing rows."""
    policy_model = apps.get_model(
        'api_permission', 'PumpwoodPermissionPolicy')
    action_model = apps.get_model(
        'api_permission', 'PumpwoodPermissionPolicyAction')
    used_codes = set()

    for policy in policy_model.objects.all().order_by('pk'):
        if policy.code not in (None, ''):
            used_codes.add(policy.code)
            continue
        policy.code = _unique_slug_code(
            text=policy.description,
            pk=policy.pk,
            used_codes=used_codes,
            prefix='policy')
        policy.save(update_fields=['code'])

    for action in action_model.objects.all().order_by('pk'):
        if action.code not in (None, ''):
            used_codes.add(action.code)
            continue
        action_text = '{policy_id}--{action_name}'.format(
            policy_id=action.policy_id,
            action_name=action.action)
        action.code = _unique_slug_code(
            text=action_text,
            pk=action.pk,
            used_codes=used_codes,
            prefix='policy-action')
        action.save(update_fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('api_permission', '0021_alter_pumpwoodpermissionpolicy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumpwoodpermissionpolicy',
            name='code',
            field=models.TextField(
                blank=True,
                null=True,
                help_text='A code to identify the permission group.',
                verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='pumpwoodpermissionpolicyaction',
            name='code',
            field=models.TextField(
                blank=True,
                null=True,
                help_text='A code to identify the permission group.',
                verbose_name='Code'),
        ),
        migrations.RunPython(
            backfill_permission_codes,
            migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pumpwoodpermissionpolicy',
            name='code',
            field=models.TextField(
                blank=True,
                null=True,
                unique=True,
                help_text='A code to identify the permission group.',
                verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='pumpwoodpermissionpolicyaction',
            name='code',
            field=models.TextField(
                blank=True,
                null=True,
                unique=True,
                help_text='A code to identify the permission group.',
                verbose_name='Code'),
        ),
    ]
