# Generated by Django 5.1.3 on 2026-06-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_permission', '0021_alter_pumpwoodpermissionpolicy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumpwoodpermissionpolicy',
            name='code',
            field=models.TextField(blank=True, help_text='A code to identify the permission group.', unique=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='pumpwoodpermissionpolicyaction',
            name='code',
            field=models.TextField(blank=True, help_text='A code to identify the permission group.', unique=True, verbose_name='Code'),
        ),
    ]
