# Generated by Django 5.1.3 on 2026-06-18 16:23
"""Add unique code field to PumpwoodUserGroup."""
from django.db import migrations, models
from slugify import slugify


def _unique_slug_code(text, pk, used_codes, prefix):
    """Build a unique code from text using slugify.

    Args:
        text (str):
            Source text, usually description.
        pk (int):
            Primary key used when slugify returns an empty string.
        used_codes (set):
            Codes already assigned in the same migration run.
        prefix (str):
            Prefix for fallback code when slugify returns empty.

    Returns:
        str:
            Unique slug code.
    """
    base = slugify(text or '')
    if base == '':
        base = '{prefix}-{pk}'.format(prefix=prefix, pk=pk)
    code = base
    suffix = 2
    while code in used_codes:
        code = '{base}-{suffix}'.format(base=base, suffix=suffix)
        suffix += 1
    used_codes.add(code)
    return code


def backfill_group_codes(apps, schema_editor):
    """Set code from slugified description for existing rows."""
    group_model = apps.get_model('groups', 'PumpwoodUserGroup')
    used_codes = set()

    for group in group_model.objects.all().order_by('pk'):
        if group.code not in (None, ''):
            used_codes.add(group.code)
            continue
        group.code = _unique_slug_code(
            text=group.description,
            pk=group.pk,
            used_codes=used_codes,
            prefix='group')
        group.save(update_fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_pumpwoodusergroupm2m_options'),
    ]

    operations = [
        migrations.RunPython(
            backfill_group_codes,
            migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pumpwoodusergroup',
            name='code',
            field=models.TextField(
                blank=True,
                unique=True,
                help_text='A code to identify the permission group.',
                verbose_name='Code'),
        ),
    ]
