# Generated by Django 5.1.3 on 2026-06-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_pumpwoodusergroupm2m_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumpwoodusergroup',
            name='code',
            field=models.TextField(blank=True, help_text='A code to identify the permission group.', unique=True, verbose_name='Code'),
        ),
    ]
